run_logged $VRINDAVAN_INSTALL/configs/config.sh
run_logged $VRINDAVAN_INSTALL/configs/theme.sh
run_logged $VRINDAVAN_INSTALL/configs/gpg.sh
run_logged $VRINDAVAN_INSTALL/configs/increase-sudo-tries.sh
run_logged $VRINDAVAN_INSTALL/configs/increase-lockout-limit.sh
run_logged $VRINDAVAN_INSTALL/configs/ssh-flakiness.sh
run_logged $VRINDAVAN_INSTALL/configs/fix-powerprofilesctl-shebang.sh
run_logged $VRINDAVAN_INSTALL/configs/docker.sh
run_logged $VRINDAVAN_INSTALL/configs/mimetypes.sh
run_logged $VRINDAVAN_INSTALL/configs/localdb.sh
run_logged $VRINDAVAN_INSTALL/configs/fast-shutdown.sh
run_logged $VRINDAVAN_INSTALL/configs/sudoless-asdcontrol.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/network.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/set-wireless-regdom.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/bluetooth.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/printer.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/usb-autosuspend.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/ignore-power-button.sh
run_logged $VRINDAVAN_INSTALL/configs/hardware/nvidia.sh
